# Uncomment the neline to define a global platform for your project
# platform :ios, '9.0'

target 'PhotoConnect' do
  # Comment the next line if you don't want to use dynamic frameworks
 
  #사진 라이브러리
  pod 'YPImagePicker'
  use_frameworks!

  # Pods for PhotoConnect

  target 'PhotoConnectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PhotoConnectUITests' do
    # Pods for testing
  end
  pod 'YPImagePicker'
end
