# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CompletionBlock' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CompletionBlock

  target 'CompletionBlockTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CompletionBlockUITests' do
    # Pods for testing
  end
  pod "KRProgressHUD"

end
