# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pagerView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for pagerView

  target 'pagerViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'pagerViewUITests' do
    # Pods for testing
  end
  pod 'FSPagerView'
  
end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.5'
            end
        end
    end
end
