# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Addadvertisement' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Addadvertisement

  target 'AddadvertisementTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AddadvertisementUITests' do
    # Pods for testing
  end
  pod 'Google-Mobile-Ads-SDK'

end
