# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SomeAnimation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SomeAnimation

  target 'SomeAnimationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SomeAnimationUITests' do
    # Pods for testing
  end
   pod 'lottie-ios'
end
